"""snapshot pinned Claude analysis"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "ba5d37137dd2"
down_revision = "d83778d7d950"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_unique_constraint(
        "uq_snapshots_tenant_patient_id", "snapshots", ["tenant_id", "patient_id", "id"]
    )
    op.create_table(
        "analysis_tasks",
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("abstraction_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("question", sa.Text(), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=50), nullable=False),
        sa.Column("schema_version", sa.String(length=50), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'abstraction' AND abstraction_id IS NULL AND question IS NULL) OR (kind = 'answer' AND abstraction_id IS NOT NULL AND question IS NOT NULL)"
        ),
        sa.CheckConstraint("kind IN ('abstraction','answer')"),
        sa.CheckConstraint("status IN ('queued','running','succeeded','failed')"),
        sa.CheckConstraint("attempt >= 0"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "patient_id", "abstraction_id"],
            ["analysis_tasks.tenant_id", "analysis_tasks.patient_id", "analysis_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "patient_id", "snapshot_id"],
            ["snapshots.tenant_id", "snapshots.patient_id", "snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "actor_id", "idempotency_key"),
        sa.UniqueConstraint("tenant_id", "patient_id", "id"),
    )
    op.create_index(op.f("ix_analysis_tasks_status"), "analysis_tasks", ["status"], unique=False)
    op.create_index(
        op.f("ix_analysis_tasks_tenant_id"), "analysis_tasks", ["tenant_id"], unique=False
    )
    op.create_table(
        "analysis_results",
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "patient_id", "task_id"],
            ["analysis_tasks.tenant_id", "analysis_tasks.patient_id", "analysis_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "task_id"),
    )
    op.create_index(
        op.f("ix_analysis_results_tenant_id"), "analysis_results", ["tenant_id"], unique=False
    )
    for table in ("analysis_tasks", "analysis_results"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_scope ON {table} USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)"
        )
        op.execute(f"GRANT SELECT, INSERT ON {table} TO ehr_app")
    op.execute(
        "GRANT UPDATE (status, attempt, lease_token, lease_until, error_code, finished_at) ON analysis_tasks TO ehr_app"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analysis_results_tenant_id"), table_name="analysis_results")
    op.drop_table("analysis_results")
    op.drop_index(op.f("ix_analysis_tasks_tenant_id"), table_name="analysis_tasks")
    op.drop_index(op.f("ix_analysis_tasks_status"), table_name="analysis_tasks")
    op.drop_table("analysis_tasks")
    op.drop_constraint("uq_snapshots_tenant_patient_id", "snapshots", type_="unique")
    # ### end Alembic commands ###
