"""automatic patient routing and import review"""

import sqlalchemy as sa
from alembic import op

revision = "d83778d7d950"
down_revision = "ea6f01a92bdd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_batches",
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "actor_id", "idempotency_key"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    op.create_index(
        op.f("ix_import_batches_tenant_id"), "import_batches", ["tenant_id"], unique=False
    )
    op.create_table(
        "import_batch_items",
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("(job_id IS NULL) != (error_code IS NULL)"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "batch_id"],
            ["import_batches.tenant_id", "import_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "job_id"],
            ["jobs.tenant_id", "jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "batch_id", "ordinal"),
    )
    op.create_index(
        op.f("ix_import_batch_items_tenant_id"), "import_batch_items", ["tenant_id"], unique=False
    )
    op.add_column(
        "patients", sa.Column("archived", sa.Boolean(), server_default="false", nullable=False)
    )
    for table in ("import_batches", "import_batch_items"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_scope ON {table} USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)"
        )
        op.execute(f"GRANT SELECT, INSERT ON {table} TO ehr_app")
    # Archive is reversible; clinical source evidence remains immutable.
    op.execute("GRANT UPDATE (archived) ON patients TO ehr_app")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("patients", "archived")
    op.drop_index(op.f("ix_import_batch_items_tenant_id"), table_name="import_batch_items")
    op.drop_table("import_batch_items")
    op.drop_index(op.f("ix_import_batches_tenant_id"), table_name="import_batches")
    op.drop_table("import_batches")
    # ### end Alembic commands ###
