/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dev-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign In */
        post: operations["sign_in_api_v1_dev_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_v1_session_get"];
        put?: never;
        post?: never;
        /** Sign Out */
        delete: operations["sign_out_api_v1_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Patients */
        get: operations["patients_api_v1_patients_get"];
        put?: never;
        /** Create Patient */
        post: operations["create_patient_api_v1_patients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Import Batches */
        get: operations["import_batches_api_v1_imports_get"];
        put?: never;
        /** Automatic Import */
        post: operations["automatic_import_api_v1_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Sources */
        post: operations["import_sources_api_v1_patients__patient_id__imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs */
        get: operations["jobs_api_v1_patients__patient_id__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Documents */
        get: operations["documents_api_v1_patients__patient_id__documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}/documents/{revision_id}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Withdraw Document
         * @description Remove a document from the case. The source stays preserved for audit; a new snapshot
         *     without it is published, and its record is rebuilt automatically when a Claude key is
         *     configured.
         */
        post: operations["withdraw_document_api_v1_patients__patient_id__documents__revision_id__withdraw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}/documents/{revision_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Document */
        post: operations["restore_document_api_v1_patients__patient_id__documents__revision_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshots */
        get: operations["snapshots_api_v1_patients__patient_id__snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/source-revisions/{revision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source */
        get: operations["source_api_v1_source_revisions__revision_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/source-revisions/{revision_id}/spans/{span_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Citation */
        get: operations["citation_api_v1_source_revisions__revision_id__spans__span_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Status */
        get: operations["model_status_api_v1_model_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Record
         * @description Queue a record build: extraction, linking and reconciliation of the snapshot's
         *     documents.
         */
        post: operations["start_record_api_v1_patients__patient_id__records_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Answer
         * @description Queue a question over a finished record build.
         */
        post: operations["start_answer_api_v1_patients__patient_id__answers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Runs
         * @description Record builds and questions, newest first.
         */
        get: operations["runs_api_v1_patients__patient_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}/runs/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Runs Version
         * @description Cheap change marker so clients poll this instead of re-downloading every run.
         */
        get: operations["runs_version_api_v1_patients__patient_id__runs_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Detail
         * @description One run with its result: the record view for a record build, the cited answer for a
         *     question.
         */
        get: operations["run_detail_api_v1_patients__patient_id__runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}/records/{run_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Record
         * @description The full reconciled record (every fact with its rule and quoted evidence) as JSON, or
         *     the readable abstraction as Markdown, as a file download.
         */
        get: operations["export_record_api_v1_patients__patient_id__records__run_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerOut */
        AnswerOut: {
            /** Status */
            status: string;
            /** Statements */
            statements: components["schemas"]["StatementOut"][];
            /** Omitted */
            omitted?: components["schemas"]["StatementOut"][];
            /** Reasons */
            reasons: string[];
        };
        /** CitationOut */
        CitationOut: {
            /** Span Id */
            span_id: string;
            /** Revision Id */
            revision_id: string;
            /** Filename */
            filename: string;
            /** Start Line */
            start_line: number;
            /** End Line */
            end_line: number;
            /** Quote */
            quote: string;
        };
        /** DocumentStatusOut */
        DocumentStatusOut: {
            /**
             * Revision Id
             * Format: uuid
             */
            revision_id: string;
            /** Withdrawn */
            withdrawn: boolean;
            /** Snapshot Id */
            snapshot_id: string | null;
        };
        /** DocumentWithdraw */
        DocumentWithdraw: {
            /** Reason */
            reason: string;
        };
        /** EventOut */
        EventOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Facts */
            facts: components["schemas"]["FactOut"][];
        };
        /** FactOut */
        FactOut: {
            /** Field */
            field: string;
            /** Values */
            values: unknown[];
            /** Status */
            status: string;
            /** Reason */
            reason: string;
            /** Citations */
            citations: components["schemas"]["CitationOut"][];
        };
        /** FindingOut */
        FindingOut: {
            /** Id */
            id: string;
            /** Date */
            date: string | null;
            /** Type */
            type: string | null;
            /** Reporter */
            reporter: string | null;
            /** Text */
            text: unknown;
            /** Status */
            status: string;
            /** Citations */
            citations: components["schemas"]["CitationOut"][];
        };
        /** GoalThreshold */
        GoalThreshold: {
            /** Threshold */
            threshold: string;
            /** Measured */
            measured: number[];
            /** Outcome */
            outcome: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportBatchOut */
        ImportBatchOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Jobs */
            jobs: components["schemas"]["JobOut"][];
            /** Issues */
            issues: components["schemas"]["ImportIssueOut"][];
        };
        /** ImportIssueOut */
        ImportIssueOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            /** Error Code */
            error_code: string;
        };
        /** JobOut */
        JobOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            /** Status */
            status: string;
            /** Attempt */
            attempt: number;
            /** Error Code */
            error_code: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Uploads */
            uploads: components["schemas"]["UploadOut"][];
        };
        /** LedgerRow */
        LedgerRow: {
            /** Id */
            id: string;
            /** Date */
            date: string | null;
            /** Weekday */
            weekday: string | null;
            /** Service */
            service: string | null;
            /** Attendance */
            attendance: string | null;
            /** Disposition */
            disposition: string | null;
            /** Minutes */
            minutes: number[];
            /** Status */
            status: string | null;
            /** Reason */
            reason: string | null;
            /** Citations */
            citations: components["schemas"]["CitationOut"][];
        };
        /** ModelStatusOut */
        ModelStatusOut: {
            /**
             * Provider
             * @default anthropic
             * @constant
             */
            provider: "anthropic";
            /** Configured */
            configured: boolean;
            /** Model */
            model: string;
            /** Engine Version */
            engine_version: string;
        };
        /** OpenItemOut */
        OpenItemOut: {
            /** Kind */
            kind: string;
            /** Subject */
            subject: string | null;
            /** Text */
            text: string;
            /** Citations */
            citations: components["schemas"]["CitationOut"][];
        };
        /** PatientCreate */
        PatientCreate: {
            /** Name */
            name: string;
            /** Mrn */
            mrn: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
        };
        /** PatientOut */
        PatientOut: {
            /** Name */
            name: string;
            /** Mrn */
            mrn: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** QuestionCreate */
        QuestionCreate: {
            /**
             * Record Id
             * Format: uuid
             */
            record_id: string;
            /** Question */
            question: string;
        };
        /** RecordCreate */
        RecordCreate: {
            /**
             * Snapshot Id
             * Format: uuid
             */
            snapshot_id: string;
        };
        /** RecordDocumentOut */
        RecordDocumentOut: {
            /** Key */
            key: string;
            /** Revision Id */
            revision_id: string | null;
            /** Filename */
            filename: string;
            /** Title */
            title: string | null;
            /** Issuer */
            issuer: string | null;
            /** Copy Of */
            copy_of: string | null;
            /** Set Aside */
            set_aside: string | null;
            /** Service Dates */
            service_dates: string[];
        };
        /** RecordView */
        RecordView: {
            /** Events Total */
            events_total: number;
            /** Facts Total */
            facts_total: number;
            /** Encounters */
            encounters: components["schemas"]["LedgerRow"][];
            /** Weeks */
            weeks: components["schemas"]["WeekRow"][];
            totals: components["schemas"]["WeekRow"] | null;
            /** Events */
            events: components["schemas"]["EventOut"][];
            /** Findings */
            findings: components["schemas"]["FindingOut"][];
            /** Documents */
            documents: components["schemas"]["RecordDocumentOut"][];
            /** Open Items */
            open_items: components["schemas"]["OpenItemOut"][];
        };
        /** RevisionOut */
        RevisionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            /** Declared Id */
            declared_id: string | null;
            /** Sha256 */
            sha256: string;
            /** Line Count */
            line_count: number;
            /** Byte Count */
            byte_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Withdrawn
             * @default false
             */
            withdrawn: boolean;
        };
        /** RunDetail */
        RunDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "engine_record" | "engine_answer";
            /**
             * Snapshot Id
             * Format: uuid
             */
            snapshot_id: string;
            /** Record Id */
            record_id: string | null;
            /** Question */
            question: string | null;
            /** Status */
            status: string;
            /** Error Code */
            error_code: string | null;
            /** Model */
            model: string;
            /** Prompt Version */
            prompt_version: string;
            /** Schema Version */
            schema_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            usage?: components["schemas"]["RunUsageOut"] | null;
            record?: components["schemas"]["RecordView"] | null;
            answer?: components["schemas"]["AnswerOut"] | null;
        };
        /** RunOut */
        RunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "engine_record" | "engine_answer";
            /**
             * Snapshot Id
             * Format: uuid
             */
            snapshot_id: string;
            /** Record Id */
            record_id: string | null;
            /** Question */
            question: string | null;
            /** Status */
            status: string;
            /** Error Code */
            error_code: string | null;
            /** Model */
            model: string;
            /** Prompt Version */
            prompt_version: string;
            /** Schema Version */
            schema_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            usage?: components["schemas"]["RunUsageOut"] | null;
        };
        /** RunUsageOut */
        RunUsageOut: {
            /** Model */
            model: string;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cost Usd */
            cost_usd: number;
            /** Calls */
            calls: number;
            /** Cached Calls */
            cached_calls: number;
        };
        /** RunVersionOut */
        RunVersionOut: {
            /** Version */
            version: string;
        };
        /** SessionOut */
        SessionOut: {
            /**
             * Actor Id
             * Format: uuid
             */
            actor_id: string;
            /** Csrf Token */
            csrf_token: string;
            /**
             * Mode
             * @default synthetic_development
             * @constant
             */
            mode: "synthetic_development";
        };
        /** SnapshotOut */
        SnapshotOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sequence */
            sequence: number;
            /** Manifest Hash */
            manifest_hash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Manifest */
            manifest: {
                [key: string]: string;
            }[];
        };
        /** SourceOut */
        SourceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            /** Declared Id */
            declared_id: string | null;
            /** Sha256 */
            sha256: string;
            /** Line Count */
            line_count: number;
            /** Byte Count */
            byte_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Withdrawn
             * @default false
             */
            withdrawn: boolean;
            /** Text */
            text: string;
            /** Spans */
            spans: components["schemas"]["SpanOut"][];
            /**
             * Segmentation
             * @default structural_v1
             * @constant
             */
            segmentation: "structural_v1";
        };
        /** SpanOut */
        SpanOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Start Char */
            start_char: number;
            /** End Char */
            end_char: number;
            /** Start Line */
            start_line: number;
            /** End Line */
            end_line: number;
            /** Quote */
            quote: string;
        };
        /** StatementOut */
        StatementOut: {
            /** Text */
            text: string;
            /** Kind */
            kind: string;
            /** Citations */
            citations: components["schemas"]["CitationOut"][];
        };
        /** UploadOut */
        UploadOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            /** Status */
            status: string;
            /** Error Code */
            error_code: string | null;
            /** Revision Id */
            revision_id: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeekRow */
        WeekRow: {
            /** Week */
            week: string;
            /** Partial */
            partial: boolean;
            /** Sessions */
            sessions: number | null;
            /** Days */
            days: number | null;
            /** Minutes */
            minutes: number[];
            /** Goal */
            goal?: string | null;
            /** Thresholds */
            thresholds?: components["schemas"]["GoalThreshold"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    sign_in_api_v1_dev_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    get_session_api_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    sign_out_api_v1_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patients_api_v1_patients_get: {
        parameters: {
            query?: {
                after?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_patient_api_v1_patients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_batches_api_v1_imports_get: {
        parameters: {
            query?: {
                after?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    automatic_import_api_v1_imports_post: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_sources_api_v1_patients__patient_id__imports_post: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
            };
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jobs_api_v1_patients__patient_id__jobs_get: {
        parameters: {
            query?: {
                after?: string | null;
            };
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    documents_api_v1_patients__patient_id__documents_get: {
        parameters: {
            query?: {
                after?: string | null;
            };
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    withdraw_document_api_v1_patients__patient_id__documents__revision_id__withdraw_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentWithdraw"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_document_api_v1_patients__patient_id__documents__revision_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshots_api_v1_patients__patient_id__snapshots_get: {
        parameters: {
            query?: {
                before?: number | null;
            };
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_api_v1_source_revisions__revision_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    citation_api_v1_source_revisions__revision_id__spans__span_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision_id: string;
                span_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_status_api_v1_model_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelStatusOut"];
                };
            };
        };
    };
    start_record_api_v1_patients__patient_id__records_post: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
            };
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_answer_api_v1_patients__patient_id__answers_post: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
            };
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_api_v1_patients__patient_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_version_api_v1_patients__patient_id__runs_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunVersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_detail_api_v1_patients__patient_id__runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_record_api_v1_patients__patient_id__records__run_id__export_get: {
        parameters: {
            query?: {
                format?: "json" | "markdown";
            };
            header?: never;
            path: {
                patient_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
